---
name: Video-FourCC-Info
version: 1.005
author:
  - 'Jonathan Yu <frequency@cpan.org>'
abstract: Perl module to retrieve information about FourCCs
license: unrestricted
build_requires:
  DBD::SQLite: 1.2
  DBI: 0
  Test::More: 0.62
  Test::NoWarnings: 0.084
requires:
  DBD::SQLite: 1.2
  DBI: 0
  perl: 5.006
recommends:
  DateTime: 0
  Video::Info::Magic: 1.01
configure_requires:
  Module::Build: 0.35
dynamic_config: 0
provides:
  Video::FourCC::Info:
    file: lib/Video/FourCC/Info.pm
    version: 1.005
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
resources:
  Ratings: http://cpanratings.perl.org/d/Video-FourCC-Info
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Video-FourCC-Info
  license: http://edwardsamuels.com/copyright/beyond/articles/public.html
  repository: http://svn.ali.as/cpan/trunk/Video-FourCC-Info
